spring:
  application:
    name: club
  datasource:
    url: jdbc:log4jdbc:mariadb://np.kcanmin.com:3306/guestbook
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: guestbook
    password: 1234
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: html
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/resources
      - templates
server:
  servlet:
    encoding:
      force: true
    # context-path: /guestbook